services:
  app:
    build: .
    ports:
      - "20001:20001"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}

      OTEL_SERVICE_NAME: file-upload-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=0.0.1
      OTEL_TRACES_SAMPLER: always_on

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - backend-network

  mysql:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: file_service

    restart: unless-stopped

    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - backend-network

  minio:
    image: minio/minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio-data:/data

    networks:
      - backend-network
  redis:
    image: redis:6.2.23-alpine

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}

    ports:
      - "6380:6379"

    command:
      - sh
      - -c
      - exec redis-server --requirepass "$$REDIS_PASSWORD"

    healthcheck:
      test: [ 'CMD-SHELL' , 'REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli ping | grep PONG' ]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped

    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
  minio-data: