spring:
  application:
    name: file_upload_service_test
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          results: TRACE
