spring:
  application:
    name: file_upload_service_dev
  datasource:
    url: jdbc:mysql://mysql:3306/file_service
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 5000
      max-lifetime: 5000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
      connect-timeout: 2s
      timeout: 2s
minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: minio123
  bucket-name: dev-bucket
  connect-timeout: 10
  read-timeout: 10
  write-timeout: 10
file:
  extension:
    allowed-list:
      - jpg
      - jpeg
      - png
      - pdf
      - txt
  mime-type:
    allowed-list:
      - image/jpeg
      - image/png
      - application/pdf
      - text/plain
  file-delete-recovery:
    deleting-timeout: 10m
    scheduler-interval: 1m
    batch-size: 10
security:
  jwt:
    secret-key: GpP5Ko/lSAodfqg3B/TJpcijh06eST3P2M0pn6ZTIYY=
    access-token-expiration: 15m
    issuer: file-upload-service
  identity-hash:
    secret-key: eWeHbeT1wLynBeNl/odFQUTNONHIPXyNTd6la4puAdc=
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: TRACE
server:
  tomcat:
    mbeanregistry:
      enabled: true
login-rate-limit:
  username-ip-max-attempts: 10
  window-duration: 1m
login-attempt:
  failure-attempts: 5
  lock-duration: 60m
