spring:
  application:
    name: file_upload_service_test
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 5000
      max-lifetime: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          results: TRACE
minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket-name: test-bucket
  connect-timeout: 30
  read-timeout: 30
  write-timeout: 30
file:
  extension:
    allowed-list:
      - jpg
      - jpeg
      - png
      - pdf
      - txt
  mime-type:
    allowed-list:
      - image/jpeg
      - image/png
      - application/pdf
      - text/plain
  file-delete-recovery:
    deleting-timeout: 10m
    scheduler-interval: 1m
    batch-size: 10